[package]
name = "slides_frontend"
version = "0.1.5"
authors = ["Eduard Knyshov <edvorg@gmail.com>"]
description = "Slides engine in rust (Usage example)"
edition = "2018"

[dependencies]
slides = { path = "../lib" }